export const METHOD_POST = 'POST';
export const METHOD_GET = 'GET';
export const METHOD_PUT = 'PUT';
export const METHOD_DELETE = 'DELETE';

export const ACTION_LOGIN = 'LOGIN';
export const ACTION_LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const ACTION_LOGIN_FAIL = 'LOGIN_FAIL';

export const ACTION_LOGOUT = 'LOGOUT';
export const ACTION_USER_INFO = 'USER_INFO';
export const ACTION_USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';

export const ACTION_CATEGORY_FIND_LIST = 'CATEGORY_FIND_LIST';
export const ACTION_CATEGORY_DELETE = 'ACTION_CATEGORY_DELETE';
export const ACTION_CATEGORY_GET = 'ACTION_CATEGORY_GET';
export const ACTION_CATEGORY_CREATE = 'ACTION_CATEGORY_CREATE';
export const ACTION_CATEGORY_EDIT = 'ACTION_CATEGORY_EDIT';


export const ACTION_MODEL_TYPE_FIND_LIST = 'ACTION_MODEL_TYPE_FIND_LIST';
export const ACTION_MODEL_TYPE_DELETE = 'ACTION_MODEL_TYPE_DELETE';
export const ACTION_MODEL_TYPE_GET = 'ACTION_MODEL_TYPE_GET';
export const ACTION_MODEL_TYPE_CREATE = 'ACTION_MODEL_TYPE_CREATE';
export const ACTION_MODEL_TYPE_EDIT = 'ACTION_MODEL_TYPE_EDIT';

export const ACTION_MODEL_TYPE_INFO_FIND_LIST = 'ACTION_MODEL_TYPE_INFO_FIND_LIST';
export const ACTION_MODEL_TYPE_INFO_DELETE = 'ACTION_MODEL_TYPE_INFO_DELETE';
export const ACTION_MODEL_TYPE_INFO_GET = 'ACTION_MODEL_TYPE_INFO_GET';
export const ACTION_MODEL_TYPE_INFO_CREATE = 'ACTION_MODEL_TYPE_INFO_CREATE';
export const ACTION_MODEL_TYPE_INFO_EDIT = 'ACTION_MODEL_TYPE_INFO_EDIT';
export const ACTION_MODEL_TYPE_INFO_GET_PARAM = 'ACTION_MODEL_TYPE_INFO_GET_PARAM';



export const ACTION_GET_NAV_ITEM = 'ACTION_GET_NAV_ITEM';


